apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-code-with-quarkus-1icl
  namespace: e2e-demos-cerx-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/test-images-protected@sha256:ae6f58d1ac33188c3398e8116bd48b14066bb6aa436acf7807c43261175321ca
        name: my-java-quarkus
        resources: {}
status: {}
